export const IMC_FAIXAS = [
	{
		max: 18.5,
		imagem: 'https://ik.imagekit.io/vzr6ryejm/fitness/imc/imc06.svg?updatedAt=1730139495334',
		categoria: 'Abaixo do Peso',
		descricao: 'Seu corpo precisa de mais energia e nutrientes. Um acompanhamento nutricional pode ajudar você a alcançar o peso ideal de forma saudável, fortalecendo sua imunidade e disposição.',
		cor: 'bg-blue-500',
		dica: 'Priorize alimentos nutritivos e consulte um nutricionista',
	},
	{
		max: 24.9,
		imagem: 'https://ik.imagekit.io/vzr6ryejm/fitness/imc/imc05.svg?updatedAt=1730139495334',
		categoria: 'Peso Ideal',
		descricao: 'Excelente! Você está na faixa de peso saudável. Continue mantendo uma alimentação balanceada e praticando atividades físicas regulares para preservar sua saúde e qualidade de vida.',
		cor: 'bg-green-500',
		dica: 'Mantenha seus hábitos saudáveis e fique ativo',
	},
	{
		max: 29.9,
		imagem: 'https://ik.imagekit.io/vzr6ryejm/fitness/imc/imc04.svg?updatedAt=1730139495334',
		categoria: 'Sobrepeso',
		descricao: 'Você está acima do peso recomendado. Pequenas mudanças na rotina alimentar e a inclusão de exercícios podem fazer grande diferença. É hora de cuidar melhor da sua saúde!',
		cor: 'bg-yellow-500',
		dica: 'Inicie atividades físicas e revise seus hábitos alimentares',
	},
	{
		max: 34.9,
		imagem: 'https://ik.imagekit.io/vzr6ryejm/fitness/imc/imc03.svg?updatedAt=1730139495334',
		categoria: 'Obesidade Grau I',
		descricao: 'Este nível de obesidade aumenta riscos à saúde. É importante buscar orientação profissional para criar um plano de emagrecimento seguro e eficaz, focando em mudanças sustentáveis.',
		cor: 'bg-orange-500',
		dica: 'Consulte um médico e nutricionista para orientação',
	},
	{
		max: 39.9,
		imagem: 'https://ik.imagekit.io/vzr6ryejm/fitness/imc/imc02.svg?updatedAt=1730139495334',
		categoria: 'Obesidade Grau II',
		descricao: 'A obesidade grau II apresenta riscos significativos à saúde. Recomendamos fortemente buscar acompanhamento médico especializado para estabelecer um tratamento adequado e seguro.',
		cor: 'bg-red-500',
		dica: 'Acompanhamento médico é essencial neste estágio',
	},
	{
		max: Infinity,
		imagem: 'https://ik.imagekit.io/vzr6ryejm/fitness/imc/imc01.svg?updatedAt=1730139495334',
		categoria: 'Obesidade Grau III',
		descricao: 'A obesidade grau III é uma condição grave que requer atenção médica urgente. Procure imediatamente um especialista para avaliar as melhores opções de tratamento para sua saúde.',
		cor: 'bg-red-700',
		dica: 'Busque acompanhamento médico especializado urgente',
	},
]